kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: bfon
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  tls:
    - hosts:
      - bfon.club
      secretName: bfon-club-prod
  rules:
    - host: bfon.club
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 5001